version: '3.8'

services:
  # nyuwdev-mysql:
  #   container_name: nyuwdev-mysql
  #   image: mysql:8.2
  #   command: --default-authentication-plugin=mysql_native_password
  #   env_file:
  #     - ./env/mysql.env
  #   ports:
  #     - '4306:3306'
  #   volumes:
  #     - ./database:/var/lib/mysql
  #   restart: unless-stopped
  nyuwdev-frankenphp:
    container_name: nyuwdev-frankenphp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ../:/var/www/nyuw_dev
      - caddy_data:/data
      - caddy_config:/config
    # depends_on:
    #   - nyuwdev-mysql
    restart: unless-stopped
    networks:
      - tunnel
    tty: true

volumes:
  caddy_data:
  caddy_config:

networks:
  tunnel:
    external: true
