---
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ../:/app
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    tty: true # Human-readable logs 
  mysql:
    container_name: mysql
    image: mysql:8.4.5
    env_file:
      - ./env/mysql.env
    ports:
      - '3309:3306'
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

