## ----------------------------
## ----- DEVCONTAINER IMAGE
## ----------------------------
ARG ALPINE_VERSION
ARG NODE_VERSION
ARG PHP_VERSION

FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS node
FROM php:${PHP_VERSION}-fpm-alpine${ALPINE_VERSION} AS devcontainer

ARG COMPOSER_VERSION

# Defining app path
WORKDIR /var/www/html

# PHP extensions installer
RUN curl -fsSL -o /usr/local/bin/install-php-extensions \
        https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
    && chmod +x /usr/local/bin/install-php-extensions

# PHP extensions
RUN install-php-extensions \
        @composer-${COMPOSER_VERSION} \
        curl \
        intl \
        mbstring \
        pdo \
        pdo_mysql \
        xdebug

# Package installation
RUN apk add --update --no-cache \
        bash \
        git

# Node installation
COPY --from=node /usr/local/include/node /usr/local/include/node
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node /usr/local/bin/node /usr/local/bin/node
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm

# Copy files to container
COPY docker/php/conf.d/10-app.dev.ini ${PHP_INI_DIR}/conf.d/
COPY docker/php/www.conf /usr/local/etc/php-fpm.d/zz-docker.conf

# PHP configuration
RUN cp ${PHP_INI_DIR}/php.ini-development ${PHP_INI_DIR}/php.ini \
    && mkdir /var/log/php-fpm

HEALTHCHECK NONE
