items:
  - label: Accueil
    page_title: Accueil
    icon: fa-solid fa-house-chimney
    route: app_index
  - label: Mon CV
    icon: fa-solid fa-user-tag
    route: app_resume
  - label: Me contacter
    icon: fa-solid fa-envelope
    route: app_contact