controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%kernel.default_locale%'
    methods: 
        - GET

admin:
    resource: ../src/Controller/Admin/
    type: annotation
    prefix: /

homepage:
    path: /
    controller: App\Controller\HomeController::index

kernel:
    resource: ../src/Kernel.php
    type: annotation
