items:
  - label: Github
    link: https://github.com/Nyuwb
    class: github
    icon: fa-github
  - label: Discord - Nyuw#0001
    link: https://discordapp.com/users/116132887438426115
    class: discord
    icon: fa-discord
  - label: Twitter
    link: https://twitter.com/Nyuwb
    class: twitter
    icon: fa-twitter
  - label: Mastodon
    link: https://fosstodon.org/@nyuw
    class: mastodon
    icon: fa-mastodon
  - label: Twitch
    link: https://www.twitch.tv/nyuw
    class: twitch
    icon: fa-twitch